export const States = {
    states: [
        { key: 1, code: "AL", value: "Alabama" },
        { key: 2, code: "AK", value: "Alaska" },
        { key: 3, code: "AS", value: "American Samoa" },
        { key: 4, code: "AZ", value: "Arizona" },
        { key: 5, code: "AR", value: "Arkansas" },
        { key: 6, code: "CA", value: "California" },
        { key: 7, code: "CO", value: "Colorado" },
        { key: 8, code: "CT", value: "Connecticut" },
        { key: 9, code: "DE", value: "Delaware" },
        { key: 10, code: "DC", value: "District Of Columbia" },
        { key: 11, code: "FM", value: "Federated States Of Micronesia" },
        { key: 12, code: "FL", value: "Florida" },
        { key: 13, code: "GA", value: "Georgia" },
        { key: 14, code: "GU", value: "Guam" },
        { key: 15, code: "HI", value: "Hawaii" },
        { key: 16, code: "ID", value: "Idaho" },
        { key: 17, code: "IL", value: "Illinois" },
        { key: 18, code: "IN", value: "Indiana" },
        { key: 19, code: "IA", value: "Iowa" },
        { key: 20, code: "KS", value: "Kansas" },
        { key: 21, code: "KY", value: "Kentucky" },
        { key: 22, code: "LA", value: "Louisiana" },
        { key: 23, code: "ME", value: "Maine" },
        { key: 24, code: "MH", value: "Marshall Islands" },
        { key: 25, code: "MD", value: "Maryland" },
        { key: 26, code: "MA", value: "Massachusetts" },
        { key: 27, code: "MI", value: "Michigan" },
        { key: 28, code: "MN", value: "Minnesota" },
        { key: 29, code: "MS", value: "Mississippi" },
        { key: 30, code: "MO", value: "Missouri" },
        { key: 31, code: "MT", value: "Montana" },
        { key: 32, code: "NE", value: "Nebraska" },
        { key: 33, code: "NV", value: "Nevada" },
        { key: 34, code: "NH", value: "New Hampshire" },
        { key: 35, code: "NJ", value: "New Jersey" },
        { key: 36, code: "NM", value: "New Mexico" },
        { key: 37, code: "NY", value: "New York" },
        { key: 38, code: "NC", value: "North Carolina" },
        { key: 39, code: "ND", value: "North Dakota" },
        { key: 40, code: "MP", value: "Northern Mariana Islands" },
        { key: 41, code: "OH", value: "Ohio" },
        { key: 42, code: "OK", value: "Oklahoma" },
        { key: 43, code: "OR", value: "Oregon" },
        { key: 44, code: "PW", value: "Palau" },
        { key: 45, code: "PA", value: "Pennsylvania" },
        { key: 46, code: "PR", value: "Puerto Rico" },
        { key: 47, code: "RI", value: "Rhode Island" },
        { key: 48, code: "SC", value: "South Carolina" },
        { key: 49, code: "SD", value: "South Dakota" },
        { key: 50, code: "TN", value: "Tennessee" },
        { key: 51, code: "TX", value: "Texas" },
        { key: 52, code: "UT", value: "Utah" },
        { key: 53, code: "VT", value: "Vermont" },
        { key: 54, code: "VI", value: "Virgin Islands" },
        { key: 55, code: "VA", value: "Virginia" },
        { key: 56, code: "WA", value: "Washington" },
        { key: 57, code: "WV", value: "West Virginia" },
        { key: 58, code: "WI", value: "Wisconsin" },
        { key: 59, code: "WY", value: "Wyoming " }
    ]
}
export default States;